-- Prosody XMPP Server Configuration for Animal Shelter MAS
-- This configuration file sets up the XMPP server for agent communication

-- Server identification
admins = { "admin@serverhello" }

-- Allow running as root for development (not recommended for production)
run_as_root = true

-- Don't daemonize - run in foreground for Docker
daemonize = false

-- Modules to enable
modules_enabled = {
    -- Generally required
    "roster";           -- Allow users to have a roster
    "saslauth";         -- Authentication for clients
    "tls";              -- Add support for secure TLS on c2s/s2s connections
    "dialback";         -- s2s dialback support
    "disco";            -- Service discovery
    "carbons";          -- Keep multiple clients in sync
    "pep";              -- Enables users to publish their avatar, mood, activity, playing music and more
    "private";          -- Private XML storage (for room bookmarks, etc.)
    "blocklist";        -- Allow users to block communications with other users
    "vcard4";           -- User profiles (stored in PEP)
    "vcard_legacy";     -- Conversion between legacy vCard and PEP Avatar, vcard

    -- Nice to have
    "version";          -- Replies to server version requests
    "uptime";           -- Report how long server has been running
    "time";             -- Let others know the time here on this server
    "ping";             -- Replies to XMPP pings with pongs
    "register";         -- Allow users to register on this server using a client
    "admin_adhoc";      -- Allows administration via an XMPP client that supports ad-hoc commands

    -- Agent-specific modules
    "mam";              -- Message Archive Management (for message history)
}

-- Modules to disable
modules_disabled = {
    -- "offline";      -- Store offline messages (might not be needed for agents)
    -- "c2s";          -- Handle client connections (needed for agents)
    -- "s2s";          -- Handle server-to-server connections (not needed for single server)
}

-- Server-to-server authentication
-- Require encryption for server-to-server connections
s2s_secure_auth = false  -- Set to true in production

-- Client-to-server settings
-- Allow registration
allow_registration = true

-- These are the SSL/TLS-related settings
-- Certificates will be auto-generated by init script
ssl = {
    key = "/var/lib/prosody/serverhello.key";
    certificate = "/var/lib/prosody/serverhello.crt";
}

-- For development, don't require encryption (allows fallback to plain auth)
c2s_require_encryption = false
s2s_require_encryption = false

-- Logging configuration
log = {
    info = "*console";  -- Log info and higher to console
    -- error = "/var/log/prosody/error.log";  -- Uncomment for file logging
}

-- HTTP modules configuration
http_ports = { 5280 }
http_interfaces = { "*", "::" }
https_ports = { 5281 }
https_interfaces = { "*", "::" }

-- Statistics
-- Enable statistics collection
statistics = "internal"

-- Rate limiting (to prevent abuse)
limits = {
    c2s = {
        rate = "10kb/s";
    };
    s2sin = {
        rate = "30kb/s";
    };
}

-- Archiving configuration (for MAM)
archive_expires_after = "1w"  -- Remove archived messages after 1 week
max_archive_query_results = 50;
default_archive_policy = false  -- Don't archive all messages by default

-- Virtual hosts
VirtualHost "serverhello"
    -- Hostname for the shelter MAS
    authentication = "internal_plain"  -- Simple authentication for development
    
    -- Storage backend
    storage = "internal"  -- Use Prosody's internal storage
    
    -- Allow all users to register
    allow_registration = true
    
    -- No restrictions on who can register
    min_seconds_between_registrations = 0

-- Enable HTTP file upload (if needed)
-- Component "upload.serverhello" "http_upload"

